# Change these first
owner: 1webdomain # Your GitHub organization or username, where this repository lives
repo: up # The name of this repository

sites:
  - name: montalti.it
    url: https://www.montalti.it
  - name: montalti.biz
    url: https://www.montalti.biz
  - name: montalti.org
    url: https://www.montalti.org
  - name: montalti.info
    url: https://www.montalti.info
  - name: montalti.net
    url: https://www.montalti.net 

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: up.montalti.win
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Monitor 
  introTitle: "**UpTime** ad intervalli di 5 minuti."
  introMessage: Pagina **real-time** di monitor siti
  navbar:
    - title: Stato
      href: /
    - title: Montalti.win
      href: https://www.montalti.win

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
